data = [
    {"name": "Alice", "age": 25, "city": "New York", "occupation": "Engineer", "salary": 70000, "experience": 3},
    {"name": "Bob", "age": 32, "city": "San Francisco", "occupation": "Designer", "salary": 85000, "experience": 7},
    {"name": "Charlie", "age": 29, "city": "Los Angeles", "occupation": "Engineer", "salary": 90000, "experience": 5},
    {"name": "David", "age": 35, "city": "New York", "occupation": "Manager", "salary": 120000, "experience": 10},
    {"name": "Eve", "age": 27, "city": "Boston", "occupation": "Analyst", "salary": 60000, "experience": 2},
    {"name": "Frank", "age": 45, "city": "San Francisco", "occupation": "Engineer", "salary": 130000, "experience": 20},
    {"name": "Grace", "age": 31, "city": "Chicago", "occupation": "Manager", "salary": 95000, "experience": 8},
    {"name": "Hannah", "age": 29, "city": "New York", "occupation": "Designer", "salary": 70000, "experience": 6},
    {"name": "Ian", "age": 40, "city": "Seattle", "occupation": "Engineer", "salary": 105000, "experience": 15},
    {"name": "Jack", "age": 26, "city": "Boston", "occupation": "Analyst", "salary": 65000, "experience": 3},
    {"name": "Karen", "age": 50, "city": "Los Angeles", "occupation": "Manager", "salary": 140000, "experience": 25},
    {"name": "Leo", "age": 28, "city": "Chicago", "occupation": "Analyst", "salary": 68000, "experience": 4},
    {"name": "Mia", "age": 34, "city": "Seattle", "occupation": "Designer", "salary": 75000, "experience": 9},
    {"name": "Nina", "age": 37, "city": "New York", "occupation": "Engineer", "salary": 110000, "experience": 12},
    {"name": "Oscar", "age": 23, "city": "Chicago", "occupation": "Intern", "salary": 35000, "experience": 1},
    {"name": "Paul", "age": 41, "city": "San Francisco", "occupation": "Manager", "salary": 125000, "experience": 18},
    {"name": "Quinn", "age": 27, "city": "Seattle", "occupation": "Analyst", "salary": 62000, "experience": 2},
    {"name": "Rachel", "age": 24, "city": "Boston", "occupation": "Intern", "salary": 40000, "experience": 1},
    {"name": "Steve", "age": 30, "city": "San Francisco", "occupation": "Engineer", "salary": 78000, "experience": 6},
    {"name": "Tina", "age": 39, "city": "Los Angeles", "occupation": "Manager", "salary": 135000, "experience": 16}
]